/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class BookEntry extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookEntry
     */
    public BookEntry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jtxtauthor = new javax.swing.JTextField();
        jtxtPublisher = new javax.swing.JTextField();
        jtxtstock = new javax.swing.JTextField();
        jtxtprize = new javax.swing.JTextField();
        jbtnsave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtBid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtavailable = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("Fill the information of Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jButton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Book Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Book Author");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Book Publisher");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Book Stock");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Book Prize");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jtxtname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 220, -1));

        jtxtauthor.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtauthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 220, -1));

        jtxtPublisher.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 220, -1));

        jtxtstock.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 220, -1));

        jtxtprize.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtprize, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 220, -1));

        jbtnsave.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jbtnsave.setText("Save");
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        jButton4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));

        jButton5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Book Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 116, -1, 20));

        jtxtBid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtBid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 220, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("Book Available");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jtxtavailable.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtavailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 220, -1));

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/aa.jpg"))); // NOI18N
        lblimg.setText("jLabel7");
        jPanel1.add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String newid = jtxtBid.getText().trim();
        int id = Integer.parseInt(newid);
      
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");
                       
            String sql = "select * from book_entry where b_id= '"+id+"' ";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            int status=0;
            
            if(rs.next()){
                status=1;
                jtxtname.setText(rs.getString("b_name"));
                jtxtauthor.setText(rs.getString("b_author"));
                jtxtPublisher.setText(rs.getString("b_publisher"));
                 jtxtstock.setText(rs.getString("b_stock"));
                  jtxtprize.setText(rs.getString("b_prize"));
                  jtxtavailable.setText(rs.getString("bavail"));
               
                
                
            
            }
            if(status==0)
                JOptionPane.showMessageDialog(null,"Not found");
                               
        } catch (Exception ex) {
            System.out.println("Exception "+ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        // TODO add your handling code here:
         try{
            
             Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
             
              String sql1="select *from book_entry where b_id='"+jtxtBid.getText()+"'";
                   PreparedStatement pst1=con.prepareStatement(sql1); 
                   ResultSet rs1=pst1.executeQuery();    
                   
                    if(rs1.next()){
                               JOptionPane.showMessageDialog(null, "ID '" + jtxtBid.getText() + "' already exists");
                    }else{
             
              String sql = "insert into book_entry(b_id,b_name,b_author,b_publisher,b_stock,b_prize,bavail)values ('"+jtxtBid.getText()+"','"+jtxtname.getText()+"','"+jtxtauthor.getText()+"','"+jtxtPublisher.getText()+"','"+jtxtstock.getText()+"','"+jtxtprize.getText()+"','"+jtxtavailable.getText()+"') ";
        PreparedStatement pst = con.prepareStatement(sql);
        int i = pst.executeUpdate();
        
        if(i>0)
            JOptionPane.showMessageDialog(null, "Saved");
        
        clear();
        con.close();
        pst.close();
        } 
         }
        catch(Exception ex){
            System.out.println("ex"+ex);
        }
    }//GEN-LAST:event_jbtnsaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
             
             
                   Class.forName("com.mysql.jdbc.Driver");
                   
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                   
                   
                 
                 
                    
                  String sql="update book_entry  set  b_name='"+jtxtname.getText()+"',b_author='"+jtxtauthor.getText()+"',b_publisher='"+jtxtPublisher.getText()+"',b_stock='"+jtxtstock.getText()+"',b_prize='"+jtxtprize.getText()+"',bavail='"+jtxtavailable.getText()+"'  where b_id='"+jtxtBid.getText()+"'";
                   
                   PreparedStatement pst=con.prepareStatement(sql);
                   int i=pst.executeUpdate();
                   if(i>0){
                       JOptionPane.showMessageDialog(null,"Record Update suceessfully");
                       
                      clear();
                       con.close();
                       pst.close();
                       
                       
                   }
         }catch(Exception ex){
             System.out.println("ex"+ex);
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
                   
                   
                   Class.forName("com.mysql.jdbc.Driver");
                   
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                   
                   String sql="delete from book_entry where b_id='"+jtxtBid.getText()+"' ";
                   
                   PreparedStatement pst=con.prepareStatement(sql);
                   int i=pst.executeUpdate();
                   if(i>0){
                       JOptionPane.showMessageDialog(null,"Record Delete suceessfully");
                   }
                   
                       
                   clear();
                          
                pst.close();
                con.close();
             
               
                         
                   
                   
                }catch(Exception ex){
                   System.out.println("ex"+ex);
               }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void clear(){
        jtxtBid.setText(" ");
        jtxtname.setText(" ");
         jtxtauthor.setText(" ");
        
        jtxtPublisher.setText(" ");
          jtxtstock.setText(" ");
           jtxtprize.setText(" ");
           jtxtavailable.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JTextField jtxtBid;
    private javax.swing.JTextField jtxtPublisher;
    private javax.swing.JTextField jtxtauthor;
    private javax.swing.JTextField jtxtavailable;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtprize;
    private javax.swing.JTextField jtxtstock;
    private javax.swing.JLabel lblimg;
    // End of variables declaration//GEN-END:variables
}
