/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.time.LocalDate;


/**
 *
 * @author HP
 */
public class IssueBook extends javax.swing.JInternalFrame {

    /**
     * Creates new form isuuedate
     */
 
       String imagename=null;
    
    public IssueBook() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtsname = new javax.swing.JTextField();
        jtxtSbranch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtSid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtSyear = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtbid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtbname = new javax.swing.JTextField();
        jtxtbstock = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtbidSearch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtxtbooknameSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblimg = new javax.swing.JLabel();
        jtxtissuedate = new javax.swing.JTextField();
        jtxtduedate = new javax.swing.JTextField();
        jlblimg = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Student Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 43, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Student Branch ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setText("Due Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jtxtsname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 40, 193, -1));

        jtxtSbranch.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtSbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 92, 193, -1));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("Issue Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 570, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setText("Enter Student Id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 43, 130, -1));

        jtxtSid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jtxtSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSidActionPerformed(evt);
            }
        });
        jtxtSid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtSidKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtSid, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 80, 119, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setText("Student Year");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 153, -1, -1));

        jtxtSyear.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtSyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 150, 193, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setText("Book Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 214, -1, -1));

        jtxtbid.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 211, 193, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setText("Book Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jtxtbname.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jPanel1.add(jtxtbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 193, -1));

        jtxtbstock.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jtxtbstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbstockActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtbstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 193, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setText("Book Stock");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel11.setText("Search Book by Book Id or Book Name :-");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel12.setText("Book Id");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        jtxtbidSearch.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jtxtbidSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbidSearchActionPerformed(evt);
            }
        });
        jtxtbidSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtbidSearchKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtbidSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 150, -1));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel13.setText("Book Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, -1, -1));

        jtxtbooknameSearch.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jtxtbooknameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtbooknameSearchActionPerformed(evt);
            }
        });
        jtxtbooknameSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtbooknameSearchKeyTyped(evt);
            }
        });
        jPanel1.add(jtxtbooknameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 150, -1));

        jTable1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 410, 369));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimg, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 133, -1, -1));

        jtxtissuedate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jtxtissuedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtissuedateFocusGained(evt);
            }
        });
        jtxtissuedate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtissuedateMouseClicked(evt);
            }
        });
        jtxtissuedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtissuedateActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 193, -1));

        jtxtduedate.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jtxtduedate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtduedateFocusGained(evt);
            }
        });
        jtxtduedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtduedateActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 193, -1));

        jlblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/bb.jpg"))); // NOI18N
        jPanel1.add(jlblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1040, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int issuedBookCount = getIssuedBookCount();
        int avail = getCurrentStock(jtxtbid.getText());
        int alreadyissue = isAlreadyissue(jtxtSid.getText(),jtxtbid.getText());
      //  if (issuedBookCount >= 3 && avail<1 && alreadyissue>0) 
      
       if (issuedBookCount >= 3 ) 
            JOptionPane.showMessageDialog(null, "Student has already issued 3 books. Limit Over.");
        else if(avail<1)
            JOptionPane.showMessageDialog(null, "Out of Stock");
        else if(alreadyissue>0)
            JOptionPane.showMessageDialog(null, "Student has already issued this book.");
    else{
        
        String bookID=jtxtsname.getText();
        String studentID=jtxtSbranch.getText();
        
      /*   java.util.Date date = jDateChooser1.getDate();
        format = new SimpleDateFormat("dd/MM/yyyy");
      String issueDate = format.format(date); */ 
      
      //second method
      
   
   //   LocalDate issueDate = LocalDate.now();

    // Calculate due date (15 days later)
  //  LocalDate dueDate = issueDate.plusDays(15);

    // Format the dates to String if needed
 /*   SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
    String formattedIssueDate = dFormat.format(java.sql.Date.valueOf(issueDate)); // Format issue date
    String formattedDueDate = dFormat.format(java.sql.Date.valueOf(dueDate)); // Format due date

    // If you want to set these dates back to JDateChooser
    jDateChooser1.setDate(java.sql.Date.valueOf(issueDate)); // Set issue date in JDateChooser
    jDateChooser2.setDate(java.sql.Date.valueOf(dueDate));   // Set due date in JDateChooser
        
    
      */ 
       
       

      String returnBook=null;
      
      int fine=0;
      
       int status = 0;
      
      try{
            status=1;
          
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
             
              String sql = "insert into issue_book(s_id,s_name,s_branch,s_year,b_id,b_name,b_stock,i_date,d_date,r_date,s_img,s_status,i_fine)values ('"+jtxtSid.getText()+"','"+jtxtsname.getText()+"','"+jtxtSbranch.getText()+"','"+jtxtSyear.getText()+"','"+jtxtbid.getText()+"','"+jtxtbname.getText()+"','"+jtxtbstock.getText()+"','"+jtxtissuedate.getText()+"','"+jtxtduedate.getText()+"','"+returnBook+"','"+imagename+"','"+status+"','"+fine+"') ";
        PreparedStatement pst = con.prepareStatement(sql);
        int i = pst.executeUpdate();
        
        if(i>0){
          
            JOptionPane.showMessageDialog(null, "Issue book Successfully");
       //   updateStudentStatus(jtxtSid.getText(), 1);
       int newavail = avail-1;
       String sql1 = "update  book_entry set bavail='"+newavail+"' where b_id='"+jtxtbid.getText()+"'";
        PreparedStatement pst1 = con.prepareStatement(sql1);
        //  ResultSet rs = pst1.executeQuery();
             
        /*    if(rs.next()){
                
                jtxtbstock.setText(""+newavail);
                    
              
            }*/
        
           int updated= pst1.executeUpdate();
                        if (updated > 0) {
                            jtxtbstock.setText(String.valueOf(newavail));
        
        
        
        con.close();
        pst.close();
        }   
        }                 
      }catch(Exception ex){
          System.out.println("ex"+ex);
          
      }
      
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtSidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSidKeyTyped
        // TODO add your handling code here:
        
         if (evt.getKeyChar()== '\n'){
           String newid = jtxtSid.getText().trim();
        int id = Integer.parseInt(newid);
      
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");
                       
            String sql = "select * from student_entry where s_id= '"+id+"' ";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            int status=0;
            
            if(rs.next()){
                status=1;
                jtxtsname.setText(rs.getString("s_name"));
               
                jtxtSbranch.setText(rs.getString("s_branch"));
                 jtxtSyear.setText(rs.getString("s_year"));
                
           
                imagename = rs.getString("s_img");
               ImageIcon icon=new ImageIcon("D:\\java\\ImageIcon\\"+imagename);
                Image image = icon.getImage();
                
                Image newImage =image.getScaledInstance(lblimg.getWidth(), lblimg.getHeight(), Image.SCALE_SMOOTH);
            lblimg.setIcon(new ImageIcon(newImage));
            
            
            }
            if(status==0)
                JOptionPane.showMessageDialog(null,"Student id is not found");
            
            
       
                               
        } catch (Exception ex) {
            System.out.println("Exception "+ex);
        }
    }                                        
    }//GEN-LAST:event_jtxtSidKeyTyped

    private void jtxtbidSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbidSearchKeyTyped
        // TODO add your handling code here:
         if (evt.getKeyChar()== '\n'){
              int status=0;
                 
                  try{
                   
                    
                  String id=jtxtbidSearch.getText().trim();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                   
                   String sql="select *from book_entry where b_id like '%"+id+"%'" ;  
                    
                   PreparedStatement pst=con.prepareStatement(sql);
                   
                  ResultSet rs=pst.executeQuery();  
                  
                   if(rs.next()){
                        status=1;
                   
                   jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                   
                  
                     
                  
                   } if(status==0){
                JOptionPane.showMessageDialog(null,"Book Id is not Available");
                }
            
       
                               
        } catch(Exception ex){
            System.out.println("ex"+ex);
        
              }
             
    }        
                                      

        
    }//GEN-LAST:event_jtxtbidSearchKeyTyped

    private void jtxtbooknameSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbooknameSearchKeyTyped
        // TODO add your handling code here:
        
             if (evt.getKeyChar()== '\n'){
                 
                 int status=0;
                  try{
             
                  String name=jtxtbooknameSearch.getText().trim();
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management","root","");
                   
                   String sql="select *from book_entry where b_name like '%"+name+"%'" ;  
                    
                   PreparedStatement pst=con.prepareStatement(sql);
                   
                  ResultSet rs=pst.executeQuery();   
                  
                   if(rs.next()){
                    status=1;
                    
                   jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                     
                     }
                   
                  if(status==0)
                JOptionPane.showMessageDialog(null,"Book is not Available");
            
            
       
                               
        }
        catch(Exception ex){
            System.out.println("ex"+ex);
        
              }
                     
             }                         

    }//GEN-LAST:event_jtxtbooknameSearchKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
         TableModel model =  jTable1.getModel();
         int row =  jTable1.getSelectedRow();
         
          int id = (int) model.getValueAt(row, 0);
          
          String name=(String)model.getValueAt(row, 1);
          
          int stock=(int)model.getValueAt(row,4);
          
          
          
          
          jtxtbid.setText(""+id);
          jtxtbname.setText(""+name);
          jtxtbstock.setText(""+stock);
          jtxtbooknameSearch.setText(""+name);
          jtxtbidSearch.setText(""+id);
          
          
          
          
          
        
        
          
    }//GEN-LAST:event_jTable1MouseClicked

    private void jtxtbooknameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbooknameSearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtbooknameSearchActionPerformed

    private void jtxtbidSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbidSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtbidSearchActionPerformed

    private void jtxtbstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtbstockActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtbstockActionPerformed

    private void jtxtSidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSidActionPerformed

    private void jtxtissuedateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtissuedateMouseClicked
        // TODO add your handling code here:
        
       //  LocalDate issueDate = LocalDate.now();
         
      //   jtxtissuedate.setText(""+issueDate);
    }//GEN-LAST:event_jtxtissuedateMouseClicked

    private void jtxtissuedateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtissuedateFocusGained
        // TODO add your handling code here:
          LocalDate issueDate = LocalDate.now();
         
         jtxtissuedate.setText(""+issueDate);
         
          jtxtissuedate.setEditable(false);
    }//GEN-LAST:event_jtxtissuedateFocusGained

    private void jtxtduedateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtduedateFocusGained
        // TODO add your handling code here:
        
         LocalDate issueDate = LocalDate.now();
        
         LocalDate dueDate = issueDate.plusDays(15);
         jtxtduedate.setText(""+dueDate);
         
         jtxtduedate.setEditable(false);
    }//GEN-LAST:event_jtxtduedateFocusGained

    private void jtxtissuedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtissuedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtissuedateActionPerformed

    private void jtxtduedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtduedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtduedateActionPerformed

    private int getIssuedBookCount() {
    int count = 0;
    String Id = jtxtSid.getText().trim();
    
    try {
           
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");
             
             String sql="SELECT COUNT(*) FROM issue_book where s_id='"+Id+"' ";
             
             PreparedStatement pst=con.prepareStatement(sql);
             
             ResultSet rs = pst.executeQuery();
             
            while(rs.next()){
                
                 count = rs.getInt(1);      
                    
              
            }
            // Update student status based on issued book count
        //     updateStudentStatus(Id, count > 0 ? 1 : 0);

            con.close();
            pst.close();
            rs.close();
       
        } catch (Exception ex) {
            System.out.println("ex"+ex);
        }
    return count;
}
  
  /*  private void updateStudentStatus(String studentId, int status) {
        String Id = jtxtSid.getText().trim();
         status=0;
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");

        String updateStatusSql = "UPDATE student_entry SET status = 1 WHERE s_id = '"+Id+"' ";
        PreparedStatement statusUpdatePst = con.prepareStatement(updateStatusSql);
       
        int i = statusUpdatePst.executeUpdate(); 

        if (i> 0) {
            System.out.println("Student status updated successfully.");
        } else {
            System.out.println("Student ID not found.");
        }
        con.close();
        statusUpdatePst.close();
    } catch (Exception ex) {
        System.out.println("Exception: " + ex);
    }
}
*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlblimg;
    private javax.swing.JTextField jtxtSbranch;
    private javax.swing.JTextField jtxtSid;
    private javax.swing.JTextField jtxtSyear;
    private javax.swing.JTextField jtxtbid;
    private javax.swing.JTextField jtxtbidSearch;
    private javax.swing.JTextField jtxtbname;
    private javax.swing.JTextField jtxtbooknameSearch;
    private javax.swing.JTextField jtxtbstock;
    private javax.swing.JTextField jtxtduedate;
    private javax.swing.JTextField jtxtissuedate;
    private javax.swing.JTextField jtxtsname;
    private javax.swing.JLabel lblimg;
    // End of variables declaration//GEN-END:variables

    private int getCurrentStock(String bookID) {
        int avail = 0;
        try {
              Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");
             
            String sql = "select bavail from book_entry where b_id='"+bookID+"'";
            
            PreparedStatement pst=con.prepareStatement(sql);
             
             ResultSet rs = pst.executeQuery();
            
            
            while(rs.next())
                
            {
               avail=rs.getInt(1); 
            }
        } catch (Exception e) {
        }
        return avail;
    }

    private int isAlreadyissue(String sid, String bid) {
         int alreadyissue = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");
             
            String sql = "select count(*) from issue_table where s_id='"+sid+"' b_id='"+bid+"'";
            
            PreparedStatement pst=con.prepareStatement(sql);
             
             ResultSet rs = pst.executeQuery();
            
            while(rs.next())
            {
                alreadyissue = rs.getInt(1);
            }
        } catch (Exception e) {
        }
        return alreadyissue;
    }
}
