/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author HP
 */
public class Statistics extends javax.swing.JInternalFrame {

    /**
     * Creates new form Statictics
     */
    public Statistics() {
        initComponents();
        
        showPieChart();
    }
    public void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset();
      
      try{
       Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_management", "root", "");
                       
            String issuedSql = "SELECT COUNT(*) AS issued_count FROM issue_book WHERE s_status = '1'";
        PreparedStatement issuedPst = con.prepareStatement(issuedSql);
        ResultSet issuedRs = issuedPst.executeQuery();
        int issuedCount = 0;
        if (issuedRs.next()) {
            issuedCount = issuedRs.getInt("issued_count");
        }

        // SQL query to count returned books
        String returnedSql = "SELECT COUNT(*) AS returned_count FROM issue_book WHERE s_status = '0'";
        PreparedStatement returnedPst = con.prepareStatement(returnedSql);
        ResultSet returnedRs = returnedPst.executeQuery();
        int returnedCount = 0;
        if (returnedRs.next()) {
            returnedCount = returnedRs.getInt("returned_count");
        }

        // Populate the dataset with counts
        barDataset.setValue("Issued Books", issuedCount);
        barDataset.setValue("Returned Books", returnedCount);
      }catch(Exception ex){
             System.out.println("ex"+ex);
                    
      }
      
      barDataset.setValue( "Issue Book" , new Double( 20 ) );  
      barDataset.setValue( "Return Book" , new Double( 20 ) );   
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Library Management System",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
       piePlot.setSectionPaint("Issue Book", new Color(255,255,102));
        piePlot.setSectionPaint("Return Book", new Color(102,255,102));
        
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBarChart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarChart.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 450, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/bb.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
